package vista;


import controlador.controlador;
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.xml.bind.Marshaller.Listener;
import modelo.acceso;
import modelo.listShow;
import modelo.show;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2dam
 */



public class PrimeraPantalla extends javax.swing.JFrame {

    
      private controlador c = null;

    
    /**
     * Creates new form PrimeraPantalla
     */
    public PrimeraPantalla( controlador control) throws IOException {
         c=control;
    initComponents();
   

    }
    

    /*
    
    
    
        setTitle("PruebaColores");
        setSize(500,500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        JPanel panel = new JPanel();
        add(panel);
        panel.setBackground(Color.red);
        JButton boton = new JButton("boton");
        Dimension d = new Dimension();
        d.height = 80;
        d.width = 200;
        boton.setPreferredSize(d);
        panel.add(boton);
        
           class listenerRed implements ActionListener{
    public void actionPerfomed (ActionEvent e){
        panel.setBackground(Color.red);
    }
}
    
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  String operacion;
  String num1;
  String num2;
  String Recurrente;
  String NumeroMS;
  boolean repetitivo=false;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        Primero = new javax.swing.JButton();
        Alante = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        Anyadir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldTitulo = new javax.swing.JTextField();
        TextFieldGuionista = new javax.swing.JTextField();
        TextFieldTemporada = new javax.swing.JTextField();
        TextFieldGenero = new javax.swing.JTextField();
        TextFieldVistas = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("fondo"); // NOI18N
        setSize(new java.awt.Dimension(9, 9));

        Atras.setText("<");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Primero.setText("/<");
        Primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroActionPerformed(evt);
            }
        });

        Alante.setText(">");
        Alante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlanteActionPerformed(evt);
            }
        });

        Ultimo.setText(">/");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });

        Anyadir.setText("+");
        Anyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnyadirActionPerformed(evt);
            }
        });

        Eliminar.setText("-");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Crear.setText("*");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        jLabel2.setText("Temporada");

        jLabel3.setText("Género");

        jLabel4.setText("Temp.Vistas");

        jLabel5.setText("Guionista");

        TextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTituloActionPerformed(evt);
            }
        });

        TextFieldGuionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldGuionistaActionPerformed(evt);
            }
        });

        TextFieldTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTemporadaActionPerformed(evt);
            }
        });

        TextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldGeneroActionPerformed(evt);
            }
        });

        TextFieldVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldVistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Alante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Anyadir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 237, Short.MAX_VALUE))
                    .addComponent(TextFieldTitulo)
                    .addComponent(TextFieldVistas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldGenero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldTemporada)
                    .addComponent(TextFieldGuionista, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(Primero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(582, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Alante)
                    .addComponent(Ultimo)
                    .addComponent(Anyadir)
                    .addComponent(Eliminar)
                    .addComponent(Crear))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextFieldGuionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addComponent(TextFieldTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldVistas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Primero)
                    .addContainerGap(265, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
 
        
          try {
              botonpulsado("Anterior");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }

        
        
        
    }//GEN-LAST:event_AtrasActionPerformed

    private void PrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroActionPerformed
       
        
          try {
              botonpulsado("Primero");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_PrimeroActionPerformed

    private void AlanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlanteActionPerformed
          try {
              botonpulsado("Siguiente");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_AlanteActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
  try {
              botonpulsado("Ultimo");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_UltimoActionPerformed

    private void AnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnyadirActionPerformed
          try {
              botonpulsado("Anyadir");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_AnyadirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         try {
              botonpulsado("Eliminar");
          } catch (IOException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_EliminarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearActionPerformed

    private void TextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTituloActionPerformed

    private void TextFieldGuionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldGuionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldGuionistaActionPerformed

    private void TextFieldTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTemporadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTemporadaActionPerformed

    private void TextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldGeneroActionPerformed

    private void TextFieldVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldVistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldVistasActionPerformed

    
  public void botonpulsado(String boton) throws IOException, FileNotFoundException, ClassNotFoundException{
      show s = new show();
      
      if(boton.equals("Primero")){
          System.out.println(s);
          s=c.primero();
      }
      
       if(boton.equals("Ultimo")){
          System.out.println(s);
          s=c.ultimo();
      }
       
      if(boton.equals("Anterior")){
          System.out.println(s);
          s=c.anterior();
      }
       if(boton.equals("Siguiente")){
          System.out.println(s);
          s=c.siguiente();
      }
       
       
       
       
           if(boton.equals("Eliminar")){
        
               System.out.println(    c.getPosition());
               
               
               acceso.EliminarLs(c.getPosition());
       }
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       if(boton.equals("Anyadir")){
    
           if(this.Anyadir.getText().equals("+")){
               //Vaciamos todos los text fields
               
                  this.TextFieldGenero.setText("");
              this.TextFieldGuionista.setText("");
               this.TextFieldTemporada.setText("");
              this.TextFieldTitulo.setText("");
              this.TextFieldVistas.setText("");

              this.Primero.setEnabled(false);
              this.Ultimo.setEnabled(false);
              this.Atras.setEnabled(false);
              this.Alante.setEnabled(false);  
              this.Eliminar.setEnabled(false);
              this.Crear.setEnabled(false);

             this.Anyadir.setText("+++");
             
              
           }else{
                  this.Primero.setEnabled(true);
              this.Ultimo.setEnabled(true);
              this.Atras.setEnabled(true);
              this.Alante.setEnabled(true);  
              this.Eliminar.setEnabled(true);
              this.Crear.setEnabled(true);
              listShow ls = new listShow();
              this.Anyadir.setText("+");
              s=llenaShow();
              ls.setShow(s);
              acceso.guardarLS(ls);
              c.nuevo(s);
                      

           }
           
           
           
           
           
       }
      actualiza(s);
  }
 
  
  private show llenaShow(){
      show s = new show (this.TextFieldTitulo.getText(), this.TextFieldGuionista.getText(), Integer.parseInt(this.TextFieldTemporada.getText()), this.TextFieldGenero.getText(), Integer.parseInt(this.TextFieldVistas.getText()));
  return s;
  }
  
  private void actualiza(show s){
      this.TextFieldTitulo.setText(s.getTitle());
            this.TextFieldGuionista.setText(s.getScriptwriter());
      this.TextFieldTemporada.setText(String.valueOf(s.getSeasons()));
            this.TextFieldGenero.setText(s.getGenre());
      this.TextFieldVistas.setText(String.valueOf(s.getViews()));


  }
    
    
    /**
     * @param args the command line arguments
     */
  
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alante;
    private javax.swing.JButton Anyadir;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Eliminar;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JButton Primero;
    private javax.swing.JTextField TextFieldGenero;
    private javax.swing.JTextField TextFieldGuionista;
    private javax.swing.JTextField TextFieldTemporada;
    private javax.swing.JTextField TextFieldTitulo;
    private javax.swing.JTextField TextFieldVistas;
    private javax.swing.JButton Ultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
