
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.xml.bind.Marshaller.Listener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2dam
 */
public class PrimeraPantalla extends javax.swing.JFrame {

    
   
    
    /**
     * Creates new form PrimeraPantalla
     */
    public PrimeraPantalla() throws IOException {
         
    initComponents();
   

    }
    

    /*
    
    
    
        setTitle("PruebaColores");
        setSize(500,500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        JPanel panel = new JPanel();
        add(panel);
        panel.setBackground(Color.red);
        JButton boton = new JButton("boton");
        Dimension d = new Dimension();
        d.height = 80;
        d.width = 200;
        boton.setPreferredSize(d);
        panel.add(boton);
        
           class listenerRed implements ActionListener{
    public void actionPerfomed (ActionEvent e){
        panel.setBackground(Color.red);
    }
}
    
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  String operacion;
  String num1;
  String num2;
  String Recurrente;
  String NumeroMS;
  boolean repetitivo=false;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        xentre1 = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        Sumar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        Multipli = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        uno1 = new javax.swing.JButton();
        CE1 = new javax.swing.JButton();
        BotonC1 = new javax.swing.JButton();
        RET1 = new javax.swing.JButton();
        BotonM = new javax.swing.JButton();
        BotonMS = new javax.swing.JButton();
        Raiz1 = new javax.swing.JButton();
        Elevado1 = new javax.swing.JButton();
        divisionResiduo2 = new javax.swing.JButton();
        BotonMC1 = new javax.swing.JButton();
        BotonMR1 = new javax.swing.JButton();
        BotonMMenos = new javax.swing.JButton();
        BotonMPlus2 = new javax.swing.JButton();
        casio = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setName("fondo"); // NOI18N
        setSize(new java.awt.Dimension(9, 9));

        xentre1.setText("1/x");
        xentre1.setPreferredSize(new java.awt.Dimension(47, 23));
        xentre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xentre1ActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(204, 204, 255));
        dos.setText("2");
        dos.setPreferredSize(new java.awt.Dimension(47, 23));
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(204, 204, 255));
        tres.setText("3");
        tres.setMaximumSize(new java.awt.Dimension(47, 23));
        tres.setMinimumSize(new java.awt.Dimension(47, 23));
        tres.setPreferredSize(new java.awt.Dimension(47, 23));
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(204, 204, 255));
        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(204, 204, 255));
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(204, 204, 255));
        seis.setText("6");
        seis.setPreferredSize(new java.awt.Dimension(47, 23));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        siete.setBackground(new java.awt.Color(204, 204, 255));
        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(204, 204, 255));
        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(204, 204, 255));
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(204, 204, 255));
        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(255, 255, 204));
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        Sumar.setBackground(new java.awt.Color(204, 255, 204));
        Sumar.setText("+");
        Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarActionPerformed(evt);
            }
        });
        Sumar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SumarKeyPressed(evt);
            }
        });

        Restar.setBackground(new java.awt.Color(204, 255, 204));
        Restar.setText("-");
        Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestarActionPerformed(evt);
            }
        });

        Multipli.setBackground(new java.awt.Color(204, 255, 204));
        Multipli.setText("*");
        Multipli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultipliActionPerformed(evt);
            }
        });

        Dividir.setBackground(new java.awt.Color(204, 255, 204));
        Dividir.setText("/");
        Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DividirActionPerformed(evt);
            }
        });

        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        uno1.setBackground(new java.awt.Color(204, 204, 255));
        uno1.setText("1");
        uno1.setPreferredSize(new java.awt.Dimension(47, 23));
        uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno1ActionPerformed(evt);
            }
        });

        CE1.setBackground(new java.awt.Color(204, 255, 255));
        CE1.setText("CE");
        CE1.setPreferredSize(new java.awt.Dimension(47, 23));
        CE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE1ActionPerformed(evt);
            }
        });

        BotonC1.setBackground(new java.awt.Color(204, 255, 255));
        BotonC1.setText("C");
        BotonC1.setPreferredSize(new java.awt.Dimension(47, 23));
        BotonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC1ActionPerformed(evt);
            }
        });

        RET1.setText("Ret");
        RET1.setPreferredSize(new java.awt.Dimension(47, 23));
        RET1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RET1ActionPerformed(evt);
            }
        });

        BotonM.setBackground(new java.awt.Color(255, 204, 204));
        BotonM.setText("M");
        BotonM.setPreferredSize(new java.awt.Dimension(47, 23));
        BotonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMActionPerformed(evt);
            }
        });

        BotonMS.setBackground(new java.awt.Color(255, 204, 204));
        BotonMS.setText("MS");
        BotonMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMSActionPerformed(evt);
            }
        });

        Raiz1.setText("Raiz");
        Raiz1.setPreferredSize(new java.awt.Dimension(47, 23));
        Raiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Raiz1ActionPerformed(evt);
            }
        });

        Elevado1.setText("X2");
        Elevado1.setPreferredSize(new java.awt.Dimension(47, 23));
        Elevado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elevado1ActionPerformed(evt);
            }
        });

        divisionResiduo2.setText("%");
        divisionResiduo2.setPreferredSize(new java.awt.Dimension(47, 23));
        divisionResiduo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionResiduo2ActionPerformed(evt);
            }
        });

        BotonMC1.setBackground(new java.awt.Color(255, 204, 204));
        BotonMC1.setText("MC");
        BotonMC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMC1ActionPerformed(evt);
            }
        });

        BotonMR1.setBackground(java.awt.Color.red);
        BotonMR1.setText("MR");
        BotonMR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMR1ActionPerformed(evt);
            }
        });

        BotonMMenos.setBackground(new java.awt.Color(255, 204, 204));
        BotonMMenos.setText("M-");
        BotonMMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMMenosActionPerformed(evt);
            }
        });

        BotonMPlus2.setBackground(new java.awt.Color(255, 204, 204));
        BotonMPlus2.setText("M+");
        BotonMPlus2.setPreferredSize(new java.awt.Dimension(47, 23));
        BotonMPlus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMPlus2ActionPerformed(evt);
            }
        });

        casio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casio-logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Multipli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CE1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonC1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(divisionResiduo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonMC1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BotonMR1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BotonMPlus2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RET1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(xentre1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Elevado1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Raiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonMS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(1, 1, 1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BotonMMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AC))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(casio, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(casio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Raiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMPlus2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMR1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divisionResiduo2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMC1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Elevado1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CE1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonC1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RET1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xentre1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Multipli, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xentre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xentre1ActionPerformed

         this.resultado.setText( String.valueOf(  1 / Float.parseFloat(this.resultado.getText()) ));
        
      
    }//GEN-LAST:event_xentre1ActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
              this.resultado.setText(this.resultado.getText() + 2);

    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
      this.resultado.setText(this.resultado.getText() + 3);
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
           this.resultado.setText(this.resultado.getText() + 4);

    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
           this.resultado.setText(this.resultado.getText() + 5);

    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
              this.resultado.setText(this.resultado.getText() + 6);

    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
             this.resultado.setText(this.resultado.getText() + 7);

    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
              this.resultado.setText(this.resultado.getText() + 8);

    }//GEN-LAST:event_ochoActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
         this.resultado.setText(this.resultado.getText() + 0);

    }//GEN-LAST:event_ceroActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
           this.resultado.setText(this.resultado.getText() + 9);

    }//GEN-LAST:event_nueveActionPerformed

    private void SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarActionPerformed
   
      
           this.OperacionMetodo("Sumar");
       
    }//GEN-LAST:event_SumarActionPerformed

    
    public void OperacionMetodo (String operacionPasada){
         operacion=operacionPasada;
       this.repetitivo=false;           
           num1= this.resultado.getText();
        
     this.resultado.setText("");
    }
    
    private void RestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestarActionPerformed
      
        this.OperacionMetodo("Restar");
    }//GEN-LAST:event_RestarActionPerformed

    private void MultipliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultipliActionPerformed
        this.OperacionMetodo("Multiplicar");
    }//GEN-LAST:event_MultipliActionPerformed

    private void DividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividirActionPerformed
           this.OperacionMetodo("Dividir");
    }//GEN-LAST:event_DividirActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
           
        if(!this.resultado.getText().contains(".")){
               this.resultado.setText(this.resultado.getText() + ".");  
        }
        
   
    }//GEN-LAST:event_puntoActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
     

       if(this.repetitivo!=true){
                 num2=this.resultado.getText();
                  this.resultado.setText("");
       }
      
            
        
  
     
       
        
       switch(operacion)
{
   // declaración case
   // los valores deben ser del mismo tipo de la expresión
   case "Sumar" :
     
  
    
 
    this.Recurrente=num1;
     this.resultado.setText((String.valueOf( Float.parseFloat(num1) +  Float.parseFloat(num2) )));
     this.num1=this.resultado.getText();
     
     
     
      break; // break es opcional
   
   case "Restar" :
       this.Recurrente=num1;
     this.resultado.setText((String.valueOf( Float.parseFloat(num1) -  Float.parseFloat(num2) )));
          this.num1=this.resultado.getText();

      break; // break es opcional
   
        case "Multiplicar" :
            this.Recurrente=num1;
     this.resultado.setText((String.valueOf( Float.parseFloat(num1) *  Float.parseFloat(num2) )));
          this.num1=this.resultado.getText();

      break; // break es opcional
      
        case "Dividir" :
            this.Recurrente=num1;
            
            try {
     this.resultado.setText((String.valueOf( Float.parseFloat(num1) /  Float.parseFloat(num2) )));
          this.num1=this.resultado.getText();

            } catch (ArithmeticException e) { // 
      System.out.println("Division by zero.");
      num1="0";
      num2="0";
      
    }
            
            
            
                    
       
   

      break; 
      
   // Podemos tener cualquier número de declaraciones de casos o case
   // debajo se encuentra la declaración predeterminada, que se usa cuando ninguno de los casos es verdadero.
   // No se necesita descanso en el case default
   default : 
      // Declaraciones
}
       
      this.repetitivo=true;  
   
        
    }//GEN-LAST:event_IgualActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
      num1="";
      num2="";
      this.resultado.setText("");
    }//GEN-LAST:event_ACActionPerformed

    private void SumarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SumarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumarKeyPressed

    private void uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno1ActionPerformed
        this.resultado.setText(this.resultado.getText() + 1);
    }//GEN-LAST:event_uno1ActionPerformed

    private void CE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE1ActionPerformed
   num1=null;
   num2=null;
   this.resultado.setText("");
    }//GEN-LAST:event_CE1ActionPerformed

    private void BotonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC1ActionPerformed
 this.resultado.setText("");
   
    }//GEN-LAST:event_BotonC1ActionPerformed

    private void RET1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RET1ActionPerformed
    
      
        
       this.resultado.setText(this.resultado.getText().substring(0 , this.resultado.getText().length()-1));
         if(    this.resultado.getText().charAt(this.resultado.getText().length() -1)=='.'){
                 this.resultado.setText(this.resultado.getText().substring(0 , this.resultado.getText().length()-1));

      }
       
            }//GEN-LAST:event_RET1ActionPerformed

    private void BotonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMActionPerformed

    private void BotonMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMSActionPerformed
      
        NumeroMS=this.resultado.getText();
                System.out.println(NumeroMS);

        
        
    }//GEN-LAST:event_BotonMSActionPerformed

    private void Raiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Raiz1ActionPerformed
         double resultado = Math.sqrt(Double.parseDouble(this.resultado.getText()));
         this.resultado.setText(String.valueOf(resultado));
         
    }//GEN-LAST:event_Raiz1ActionPerformed

    private void Elevado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elevado1ActionPerformed
       int resultado = (int) Math.pow(Integer.parseInt(this.resultado.getText()), 2);
                this.resultado.setText(String.valueOf(resultado));

    }//GEN-LAST:event_Elevado1ActionPerformed

    private void divisionResiduo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionResiduo2ActionPerformed
       
    
            try {
         this.resultado.setText((String.valueOf( Float.parseFloat(num1) %  Float.parseFloat(num2) )));
          this.num1=this.resultado.getText();

            } catch (ArithmeticException e) { // 
      System.out.println("Division by zero.");
      num1="0";
      num2="0";
            }      
    }//GEN-LAST:event_divisionResiduo2ActionPerformed

    private void BotonMC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMC1ActionPerformed

NumeroMS=null;


        
        
        
    }//GEN-LAST:event_BotonMC1ActionPerformed

    private void BotonMR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMR1ActionPerformed
   
       if(NumeroMS!=null){
              this.resultado.setText(NumeroMS);
                      System.out.println(NumeroMS);

       } 
     
    }//GEN-LAST:event_BotonMR1ActionPerformed

    private void BotonMMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMMenosActionPerformed
      
        
        //     this.resultado.setText((String.valueOf( Float.parseFloat(num1) *  Float.parseFloat(num2) )));
NumeroMS= String.valueOf(  Float.parseFloat(NumeroMS)  - Float.parseFloat(this.resultado.getText()));
        System.out.println(NumeroMS);

        
    }//GEN-LAST:event_BotonMMenosActionPerformed

    private void BotonMPlus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMPlus2ActionPerformed
    NumeroMS= String.valueOf(Float.parseFloat(this.resultado.getText()) + Float.parseFloat(NumeroMS));
        System.out.println(NumeroMS);

    }//GEN-LAST:event_BotonMPlus2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrimeraPantalla().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PrimeraPantalla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton BotonC1;
    private javax.swing.JButton BotonM;
    private javax.swing.JButton BotonMC1;
    private javax.swing.JButton BotonMMenos;
    private javax.swing.JButton BotonMPlus2;
    private javax.swing.JButton BotonMR1;
    private javax.swing.JButton BotonMS;
    private javax.swing.JButton CE1;
    private javax.swing.JButton Dividir;
    private javax.swing.JButton Elevado1;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multipli;
    private javax.swing.JButton RET1;
    private javax.swing.JButton Raiz1;
    private javax.swing.JButton Restar;
    private javax.swing.JButton Sumar;
    private javax.swing.JLabel casio;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton divisionResiduo2;
    private javax.swing.JButton dos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton punto;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno1;
    private javax.swing.JButton xentre1;
    // End of variables declaration//GEN-END:variables
}
