
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.xml.bind.Marshaller.Listener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2dam
 */
public class PrimeraPantalla extends javax.swing.JFrame {

    
   
    
    /**
     * Creates new form PrimeraPantalla
     */
    public PrimeraPantalla() {
         
    initComponents();
    
    this.GrupoBotones.add(CursivaButton);
        this.GrupoBotones.add(NegritaAndCursivaButton);
            this.GrupoBotones.add(NegritaButton);
    this.GrupoBotones.add(SimpleButton );


    
    }
    
 
    /*
    
    
    
        setTitle("PruebaColores");
        setSize(500,500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        JPanel panel = new JPanel();
        add(panel);
        panel.setBackground(Color.red);
        JButton boton = new JButton("boton");
        Dimension d = new Dimension();
        d.height = 80;
        d.width = 200;
        boton.setPreferredSize(d);
        panel.add(boton);
        
           class listenerRed implements ActionListener{
    public void actionPerfomed (ActionEvent e){
        panel.setBackground(Color.red);
    }
}
    
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        NegritaButton = new javax.swing.JRadioButton();
        CursivaButton = new javax.swing.JRadioButton();
        SimpleButton = new javax.swing.JRadioButton();
        NegritaAndCursivaButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("fondo"); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        NegritaButton.setText("Negrita");
        NegritaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegritaButtonActionPerformed(evt);
            }
        });

        CursivaButton.setText("Cursiva");
        CursivaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursivaButtonActionPerformed(evt);
            }
        });

        SimpleButton.setText("Simple");
        SimpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleButtonActionPerformed(evt);
            }
        });

        NegritaAndCursivaButton.setText("Negrita/Cursiva");
        NegritaAndCursivaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegritaAndCursivaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(SimpleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NegritaButton)
                        .addGap(18, 18, 18)
                        .addComponent(CursivaButton)
                        .addGap(18, 18, 18)
                        .addComponent(NegritaAndCursivaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NegritaButton)
                    .addComponent(NegritaAndCursivaButton)
                    .addComponent(CursivaButton)
                    .addComponent(SimpleButton))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SimpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleButtonActionPerformed

this.jTextField1.setFont(this.jTextField1.getFont().deriveFont(Font.PLAIN, 14f));
    }//GEN-LAST:event_SimpleButtonActionPerformed

    private void NegritaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegritaButtonActionPerformed
this.jTextField1.setFont(this.jTextField1.getFont().deriveFont(Font.BOLD, 14f));
    }//GEN-LAST:event_NegritaButtonActionPerformed

    private void CursivaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursivaButtonActionPerformed
this.jTextField1.setFont(this.jTextField1.getFont().deriveFont(Font.ITALIC, 14f));
    }//GEN-LAST:event_CursivaButtonActionPerformed

    private void NegritaAndCursivaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegritaAndCursivaButtonActionPerformed
this.jTextField1.setFont(this.jTextField1.getFont().deriveFont(Font.BOLD + Font.ITALIC ,  14f));
    }//GEN-LAST:event_NegritaAndCursivaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CursivaButton;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JRadioButton NegritaAndCursivaButton;
    private javax.swing.JRadioButton NegritaButton;
    private javax.swing.JRadioButton SimpleButton;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
